pipeline{
  agent any
  environment{
    imagename= "myapp"
  }
  stages{
    stage('checkout') {
      steps{
      git branch:'main' , url: 
      }
    }
    stage('build image')  {
      steps{
        sh "docker build -t ${imagename} ."
      }
    }
     stage('Clean Existing Containers') {
            steps {
                // Remove any running/existing container of this image
                sh "docker rm -f \$(docker ps -aq --filter ancestor=${imagename}) || true"
            }
        }
    stage('run container') {
      steps{ 
        sh "docker run -d -p 5000:5000 ${imagename}"
      }
    }
  }
}