pipeline {
    agent any

    environment {
        ECR_URI = "641944126006.dkr.ecr.ap-south-1.amazonaws.com/project-6"
        IMAGE_NAME = "myimage"
        AWS_REGION = "ap-south-1"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/sai1919-git/projects'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonarqube') {
                    dir('project-6') {
                        script {
                            def scannerHome = tool 'sonarqube'
                            sh """
                            echo "Using scanner at: ${scannerHome}"
                            ${scannerHome}/bin/sonar-scanner \
                              -Dsonar.projectKey=project-6 \
                              -Dsonar.sources=.
                            """
                        }
                    }
                }
            }
        }

        stage('Quality Gate') {
    steps {
        timeout(time: 1, unit: 'MINUTES') {
            script {
                try {
                    waitForQualityGate abortPipeline: true
                } catch (e) {
                    echo "Quality Gate slow; check manually in SonarQube UI"
                }
            }
        }
    }
}

        stage('Docker Build') {
            steps {
                dir('project-6') {
                    sh "docker build -t $IMAGE_NAME ."
                }
            }
        }

        stage('Login to ECR') {
            steps {
                sh """
                aws ecr get-login-password --region $AWS_REGION | \
                docker login --username AWS --password-stdin $ECR_URI
                """
            }
        }

        stage('Push to ECR') {
            steps {
                sh """
                aws ecr create-repository --repository-name project-6 --region $AWS_REGION || true
                docker tag $IMAGE_NAME:latest $ECR_URI:latest
                docker push $ECR_URI:latest
                """
            }
        }

        stage('Deploy to EKS') {
            steps {
                dir('project-6') {
                    sh """
                    sed -i 's|IMAGE_URI|$ECR_URI:latest|g' deployment.yaml
                    kubectl apply -f deployment.yaml
                    kubectl apply -f service.yaml
                    """
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline completed successfully! 🎉"
        }
        failure {
            echo "Pipeline failed! ❌ Check logs."
        }
    }
}
