pipeline{
  agent any
  environment{
    AWS_REGION = "ap-south-1"
    ECR_REPO   = "641944126006.dkr.ecr.ap-south-1.amazonaws.com/project-4"
    IMAGE_NAME = "project4image"
    IMAGE_TAG  = "${BUILD_NUMBER}"
  }
  stages{
    stage('checkout'){
      steps{
        git branch:'main', url:'https://github.com/sai1919-git/projects.git'
      }
    }
    stage('build'){
      steps{
        dir('projects/project-4'){
        sh "docker build -t $IMAGE_NAME:$IMAGE_TAG ."
        }
      }
    }
    stage('ecr login'){
      steps{
        sh """ aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO """
      }
    }
    stage('tag image') {
      steps{
        sh """ docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG """
      }
    }
    stage('push image'){
      steps{
        sh "docker push $ECR_REPO:$IMAGE_TAG"
      }
    }
  }
}
